name: CI/CD
run-name: Basic CI/CD workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn package
      - name: delete fpij.db file
        run: rm fpij.db
      - name: delete test.db file
        run: rm test.db
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: mvn test
      - name: delete fpij.db file
        run: rm fpij.db
      - name: delete test.db file
        run: rm test.db
